[profile.default]
src = "src"
out = "out"
libs = ["lib"]
etherscanApiKey="etherscanApiKey"
sepolia = "AlchemyURL"





# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
